export { Header } from "./header"
export { HeroSection } from "./hero-section"
export { FeaturesSection } from "./features-section"
export { HowItWorksSection } from "./how-it-works-section"
export { ProjectsSection } from "./projects-section"
export { TestimonialsSection } from "./testimonials-section"
export { CTASection } from "./cta-section"
export { Footer } from "./footer"
